apiVersion: v1
kind: ConfigMap
metadata:
  name: headscale-config
  namespace: headscale
data:
  config.yaml: |
    server_url: https://headscale.niaefeup.pt
    listen_addr: 0.0.0.0:8080
    metrics_listen_addr: 0.0.0.0:9090

    unix_socket: /var/lib/headscale/headscale.sock

    private_key_path: /var/lib/headscale/private.key
    noise:
      private_key_path: /var/lib/headscale/noise_private.key

    prefixes:
      v4: 100.64.0.0/10
      v6: fd7a:115c:a1e0::/48

    database:
      type: sqlite
      sqlite:
        path: /var/lib/headscale/db.sqlite

    dns:
      magic_dns: true
      base_domain: vpn.niaefeup.pt
      nameservers:
        global:
          - 1.1.1.1

    derp:
      server:
        enabled: false
      urls:
        - https://controlplane.tailscale.com/derpmap/default
      paths: []
      auto_update_enabled: true
      update_frequency: 24h
