config:
  server_url: https://headscale.niaefeup.pt
  metrics_listen_addr: 0.0.0.0:9090

ingress:
  enabled: false

persistence:
  config:
    enabled: true
    storageClass: "longhorn-retain"
    accessMode: ReadWriteOnce
    size: 2Gi
