apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: grafana-https
  namespace: monitoring
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`grafana.niaefeup.pt`)
      kind: Rule
      services:
        - name: kube-prometheus-grafana
          port: 80
  tls:
    secretName: grafana-cert
---

