apiVersion: longhorn.io/v1beta1
kind: RecurringJob
metadata:
  name: snapshot
  namespace: longhorn-system
spec:
  cron: "0 0,12 * * *"
  task: "snapshot"
  groups:
    - default
  # Last 3 days
  retain: 6
  concurrency: 2
  labels:
    source: "default-group"