services:
  rpi-simulator:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rpi-simulator
    hostname: rpi-gateway
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    sysctls:
      net.ipv4.ip_forward: "1"
      net.ipv6.conf.all.forwarding: "1"
    ports:
      - "2222:22"
    restart: unless-stopped
    networks:
      kind:
        ipv4_address: 172.28.0.250

networks:
  kind:
    external: true
