---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: etcd-backup-sa
  namespace: etcd-backup
  labels:
    app: etcd-backup
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: etcd-backup-role
  namespace: etcd-backup
  labels:
    app: etcd-backup
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: etcd-backup-binding
  namespace: etcd-backup
  labels:
    app: etcd-backup
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: etcd-backup-role
subjects:
  - kind: ServiceAccount
    name: etcd-backup-sa
    namespace: etcd-backup
