apiVersion: v1
kind: Secret
metadata:
  name: etcd-backup-s3-credentials
  namespace: etcd-backup
  labels:
    app: etcd-backup
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: a9666fda18fc2da4e4087f912702a96d
  AWS_SECRET_ACCESS_KEY: 718c137c35804dd2bc783eaec9697760d3cb0f905e6ec0973462f80d96b61baf
  AWS_ENDPOINT_URL: https://953bb0a9ee1934ef47b66fb2217f4d5a.r2.cloudflarestorage.com
  AWS_S3_BUCKET: etcd
