apiVersion: v1
kind: Secret
metadata:
  name: etcd-backup-s3-credentials
  namespace: etcd-backup
  labels:
    app: etcd-backup
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: <FILL-IN>
  AWS_SECRET_ACCESS_KEY: <FILL-IN>
  AWS_ENDPOINT_URL: <FILL-IN>
  AWS_S3_BUCKET: etcd
