---
apiVersion: v1
kind: Secret
metadata:
  name: nijobs-be-secrets
  namespace: nijobs
type: Opaque
stringData:
  DB_URI: <FILL-IN>

  GOD_TOKEN: <FILL-IN>
  ACCESS_CONTROL_ALLOW_ORIGINS: <FILL-IN>
  MAIL_FROM: <FILL-IN>
  MAIL_FROM_PASSWORD: <FILL-IN>
  WEBSERVER_HOST: <FILL-IN>

  CLOUDINARY_URL: <FILL-IN>

  SESSION_SECRET: <FILL-IN>
  PORT: <FILL-IN>
  JWT_SECRET: <FILL-IN>

  PASSWORD_RECOVERY_LINK: <FILL-IN>

  ADMIN_EMAIL: <FILL-IN>
  ADMIN_PASSWORD: <FILL-IN>
---
apiVersion: v1
kind: Secret
metadata:
  name: nijobs-fe-secrets
  namespace: nijobs
type: Opaque
stringData:
  HOST_PORT: <FILL-IN>
  PUBLIC_URL: <FILL-IN>
  REACT_APP_API_HOSTNAME: <FILL-IN>
  REACT_APP_BASE_ROUTE: <FILL-IN>

# Google Analytics' Universal ID
  ANALYTICS_ID: <FILL-IN>

# Geolocation Rapid Api key
  GEO_API_KEY: <FILL-IN>
---
apiVersion: v1
kind: Secret
metadata:
  name: nijobs-locations-secrets
  namespace: nijobs
type: Opaque
stringData:
  DB_HOST: <FILL-IN>
  # Specifies the port for the mongodb database
  DB_PORT: <FILL-IN>
  # For use with external databases mostly, which might require mongodb+srv://something syntax
  DB_URI: <FILL-IN>
  # Specifies the name of the database to connect to
  DB_NAME: <FILL-IN>

  # Specifies the port in which the app will be exposed
  PORT: <FILL-IN>

  # GOD Token - OVERRIDE IN PRODUCTION
  GOD_TOKEN: <FILL-IN>

  #CORS allowed origin - OVERRIDE IN PRODUCTION
  ACCESS_CONTROL_ALLOW_ORIGIN: <FILL-IN>
