---
- name: Pre-setup - get correct interfaces
  ansible.builtin.import_playbook: networking/get-interface-playbook.yaml
- name: Networking - Router BGP
  ansible.builtin.import_playbook: networking/router-bgp-playbook.yaml
- name: Networking - Controlplane BGP
  ansible.builtin.import_playbook: networking/controlplane-bgp-playbook.yaml
