---
- name: Install Router VMs
  ansible.builtin.import_playbook: router/build-router-vm-playbook.yaml
- name: Create a set new SSH key for clusters and routers
  ansible.builtin.import_playbook: networking/add-ssh-key-to-nodes-playbook.yaml
- name: Networking - Setup static internal IPs
  ansible.builtin.import_playbook: networking/dhcp-server-config-playbook.yaml
- name: Wait for connection
  hosts: all
  connection: local
  gather_facts: false
  tasks:
    - name: Wait for nodes to change dhcp address
      ansible.builtin.wait_for:
        port: 22
        host: '{{ (ansible_ssh_host | default(ansible_host)) | default(inventory_hostname) }}'
        search_regex: OpenSSH
        delay: 10
        timeout: 120
- name: Pre-setup - get correct interfaces
  ansible.builtin.import_playbook: networking/get-interface-playbook.yaml
- name: Networking - Router BGP
  ansible.builtin.import_playbook: networking/router-bgp-playbook.yaml
- name: Networking - VRRP
  ansible.builtin.import_playbook: networking/router-vrrp-playbook.yaml
- name: Networking - Router Controlplane HA
  ansible.builtin.import_playbook: networking/controlplane-ha-playbook.yaml
- name: Nodes - Enable EPEL repositories
  ansible.builtin.import_playbook: node/add-epel-repos-playbook.yaml
