---
- name: Pre-setup - get correct interfaces
  ansible.builtin.import_playbook: networking/get-interface-playbook.yaml
- name: Networking - Router BGP
  ansible.builtin.import_playbook: networking/router-bgp-playbook.yaml
- name: Networking - VRRP
  ansible.builtin.import_playbook: networking/router-vrrp-playbook.yaml
- name: Networking - Router Controlplane HA
  ansible.builtin.import_playbook: networking/controlplane-ha-playbook.yaml
- name: Node - Pre-setup K8S
  ansible.builtin.import_playbook: k8s/node-k8s-pre-setup-playbook.yaml
- name: Setup K8s on control-plane
  ansible.builtin.import_playbook: k8s/rke-first-setup-playbook.yaml
