- name: Build router VM in hosts that have the appropriate NICs
  hosts: controlplane[0]
  tasks:
    - name: Build VM disk image
      ansible.builtin.include_tasks:
        file: "vm-image-task.ansible.yaml"
    - name: Create VM for router
      become: true
      community.libvirt.virt:
        autostart: true
        name: routerVM
        command: define
        xml: "{{ lookup('template', 'templates/libvirt-xml.j2') }}"
    - name: Start VM
      become: true
      community.libvirt.virt:
        name: routerVM
        state: running
