- name: Update initramfs
  become: true
  ansible.builtin.command:
    cmd: dracut -f -v
  changed_when: true
- name: Get current kernel version for reboot
  ansible.builtin.command:
    cmd: uname -r
  register: kernel_version
  changed_when: false
- name: Reboot using kexec to apply the driver changes
  become: true
  ansible.builtin.reboot:
    reboot_command: "kexec /boot/vmlinuz-{{ kernel_version.stdout }} --initrd=/boot/initramfs-{{ kernel_version.stdout }}.img --reuse-cmdline"
- name: Re-gather facts because pci information might be outdated
  ansible.builtin.gather_facts:
