- name: "Install virtualization utils"
  become: true
  ansible.builtin.dnf:
    name:
      - qemu-kvm
      - libvirt
      - virt-install
      - guestfs-tools
    state: present
- name: "Enable libvirt service"
  become: true
  ansible.builtin.systemd:
    name: libvirtd
    state: "started"
    enabled: true
- name: "Create VM disks folder"
  become: true
  ansible.builtin.file:
    recurse: true
    state: directory
    path: "/srv/vm/disks"
    mode: "770"
    group: qemu
- name: "Create router disk folder"
  become: true
  ansible.builtin.file:
    recurse: true
    state: directory
    path: "/srv/vm/disks/router"
    mode: "770"
    group: qemu
- name: "Download router QCOW2 file"
  become: true
  ansible.builtin.get_url:
    url: https://cloud.debian.org/images/cloud/bookworm/20240211-1654/debian-12-generic-amd64-20240211-1654.qcow2
    dest: /srv/vm/disks/router/router.qcow2
    checksum: sha512:b679398972ba45a60574d9202c4f97ea647dd3577e857407138b73b71a3c3c039804e40aac2f877f3969676b6c8a1ebdb4f2d67a4efa6301c21e349e37d43ef5
    mode: "770"
- name: "Resize router QCOW2 file"
  become: true
  ansible.builtin.command:
    cmd: qemu-img resize /srv/vm/disks/router/router.qcow2 5G

- name: "Resize router QCOW2 partition"
  block:
    - name: "Change old file router name"
      become: true
      ansible.builtin.command:
        cmd: cp /srv/vm/disks/router/router.qcow2 /srv/vm/disks/router/router.qcow2.old
        creates: /srv/vm/disks/router/router.qcow2.old
    - name: "Resize filesystem partition for router"
      become: true
      ansible.builtin.command:
        cmd: virt-resize --expand /dev/sda1 /srv/vm/disks/router/router.qcow2.old /srv/vm/disks/router/router.qcow2
    - name: "Delete old router qcow file"
      become: true
      ansible.builtin.file:
        path: /srv/vm/disks/router/router.qcow2.old
        state: absent

- name: Create user on vm
  become: true
  ansible.builtin.command:
    cmd: virt-customize -a /srv/vm/disks/router/router.qcow2 --run-command 'useradd -m -s /bin/bash -g sudo ni'

- name: Create password on user
  become: true
  ansible.builtin.command:
    cmd: virt-customize -a /srv/vm/disks/router/router.qcow2 --run-command 'echo "ni:n1bl04t:)" | chpasswd'

- name: "Create mount directory"
  become: true
  ansible.builtin.file:
    state: directory
    path: "/mnt/router"

- name: Update package repos
  become: true
  ansible.builtin.command:
    cmd: virt-customize -a /srv/vm/disks/router/router.qcow2 --run-command 'apt-get update'
- name: Install Avahi on VM
  become: true
  ansible.builtin.command:
    cmd: virt-customize -a /srv/vm/disks/router/router.qcow2 --run-command 'apt-get install -y avahi-daemon avahi-utils'

- block:
    - name: "Mount router image"
      become: true
      ansible.builtin.command: guestmount -a /srv/vm/disks/router/router.qcow2 -m /dev/sda3 /mnt/router
      register: image_create_dev
      failed_when: image_create_dev.rc != 0
    - name: Create .ssh folder on vm
      become: true
      ansible.builtin.file:
        path: /mnt/router/home/{{ ansible_ssh_user }}/.ssh
        state: directory
        owner: "{{ ansible_ssh_user }}"
        group: "{{ ansible_ssh_user }}"
        mode: "755"
    - name: Copy authorized_keys to vm
      become: true
      ansible.builtin.copy:
        src: /home/ni/.ssh/authorized_keys
        dest: /mnt/router/home/ni/.ssh/authorized_keys
        remote_src: true
        mode: "644"
    - name: Copy avahi dhcp fallback to vm
      become: true
      ansible.builtin.copy:
        src: templates/00-ipv4ll.network
        dest: /mnt/router/etc/systemd/network/00-ipv4ll.network
        mode: "644"
    - name: Copy interface network config to vm
      become: true
      ansible.builtin.template:
        src: templates/01-external.network.j2
        dest: /mnt/router/etc/systemd/network/01-external.network
        mode: "644"
    - name: Setup internal network config to vm
      become: true
      ansible.builtin.template:
        src: templates/02-internal.network.j2
        dest: /mnt/router/etc/systemd/network/02-internal.network
        mode: "644"
    - name: Add nameserver to VM
      become: true
      ansible.builtin.lineinfile:
        src: /mnt/router/etc/resolvconf/resolv.conf.d/tail
        line: nameserver 1.1.1.1
        create: yes
    - name: Enable avahi discoverability
      become: true
      ansible.builtin.lineinfile:
        path: /mnt/router/etc/avahi/avahi-daemon.conf
        regexp: '^publish-workstation='
        line: publish-workstation=yes
  always:
    - name: "Umount router partition"
      become: true
      ansible.builtin.command:
        cmd: guestunmount /mnt/router
      failed_when: false

- name: Fix grub on VM
  become: true
  ansible.builtin.command:
    cmd: virt-customize -a /srv/vm/disks/router/router.qcow2 --run-command 'grub-install /dev/sda'
