
minio:
  enabled: true
global:
    dnsService:  "rke2-coredns-rke2-coredns"
loki:
  schema_config:
    configs:
      - from: "2024-11-01"
        object_store: s3
        store: tsdb
        schema: v13
        index:
          prefix: index_
          period: 24h 