grafana:
  defaultDashboardsTimezone: Europe/Lisbon
  enabled: true
  adminPassword:<FILL-IN> 

  additionalDataSources:
    - name: Loki
      type: loki
      access: proxy
      url: http://loki-gateway.monitoring.svc.cluster.local/
      isDefault: false
