grafana:
  defaultDashboardsTimezone: Europe/Lisbon
  enabled: true
  adminPassword: tosta-mista-789  # TODO: Change password

  additionalDataSources:
    - name: Loki
      type: loki
      # basicAuth: true
      # basicAuthUser: ni
      # basicAuthPassword: pass  # TODO: Change password
      access: proxy
      url: http://loki-gateway.monitoring.svc.cluster.local/
      isDefault: false
