---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cnpg-cluster
spec:
  instances: 3

  bootstrap:
    initdb:
      database: tts-db
      owner: tts
      secret:
        name: tts-secret

  managed:
    roles:
      - name: ni
        login: true
        superuser: true
        ensure: present
        passwordSecret:
          name: ni-secret
      - name: plausible
        ensure: present
        createdb: false
        login: true
        passwordSecret:
          name: plausible-secret
      - name: sinf-website-2023
        ensure: present
        createdb: false
        login: true
        passwordSecret:
          name: sinf-website-2023-secret

  storage:
    size: 10Gi
    storageClass: longhorn-strict-local-retain
