---
apiVersion: v1
stringData:
  password: <FILL-IN>
  username: tts
kind: Secret
metadata:
  name: tts-secret
  namespace: pg
type: kubernetes.io/basic-auth
---
apiVersion: v1
stringData:
  password: <FILL-IN>
  username: tts-staging
kind: Secret
metadata:
  name: tts-staging-secret
type: kubernetes.io/basic-auth
---
apiVersion: v1
stringData:
  password: <FILL-IN>
  username: ni
kind: Secret
metadata:
  name: ni-secret
  namespace: pg
type: kubernetes.io/basic-auth
---
apiVersion: v1
stringData:
  password: <FILL-IN>
  username: plausible
kind: Secret
metadata:
  name: plausible-secret
  namespace: pg
type: kubernetes.io/basic-auth
---
apiVersion: v1
stringData:
  password: <FILL-IN>
  username: sinf-website-2023
kind: Secret
metadata:
  name: sinf-website-2023-secret
  namespace: pg
type: kubernetes.io/basic-auth