---
apiVersion: v1
kind: Namespace
metadata:
  name: external-dns-test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-server
  namespace: external-dns-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-server
  template:
    metadata:
      labels:
        app: echo-server
    spec:
      containers:
      - name: echo
        image: ealen/echo-server:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: echo-server
  namespace: external-dns-test
spec:
  selector:
    app: echo-server
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: test-external-dns
  namespace: external-dns-test
  annotations:
    external-dns.alpha.kubernetes.io/target: traefik.kube-system.svc.cluster.local
spec:
  entryPoints:
    - web
    - websecure
  routes:
  - match: Host(`test.niaefeup.pt`)
    kind: Rule
    services:
    - name: echo-server
      port: 80
