kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: niployments-test-cluster
nodes:
  - role: control-plane
  - role: control-plane
  - role: control-plane
  - role: worker
  - role: worker 

containerdConfigPatches:
  - |-
    [plugins."io.containerd.grpc.v1.cri".registry.configs."172.28.255.200".tls]
      insecure_skip_verify = true
