apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: daily-snapshot
  namespace: longhorn-system
spec:
  concurrency: 1
  cron: 0 2 * * *
  groups:
  - default
  name: daily-snapshot
  retain: 3
  task: snapshot