---
apiVersion: v1
kind: Namespace
metadata:
  name: external-dns
---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-key
  namespace: external-dns
type: Opaque
stringData:
  apiKey: <FILL-IN-YOUR-CLOUDFLARE-TOKEN-HERE>
