provider:
  name: cloudflare

sources:
  - ingress
  - service
  - traefik-proxy

env:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cloudflare-api-key
        key: apiKey

extraArgs:
  - --txt-owner-id=niployments
  - --txt-prefix=external-dns-
  - --interval=5m0s
  - --cloudflare-proxied
  - --domain-filter=niaefeup.pt
