# Default values for minecraft.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# ********REQUIRED********
node:
  hostname: 'dell3' # Your kube node's hostname
# ************************

minecraft:
  type: 'PAPER'
  version: '1.20.4'
  gamemode: 'survival'
  motd: 'Your super-cool, super-kube, minecraft server' # Message of the Day
  port: 30565

volume:
  storage: 3Gi
  path: '/home/augusto/NI/miNIcraft/data2' # Path to wherever you want to save your worldfile

resources:
  limits:
    memory: 2Gi
  requests:
    memory: 1.5Gi

serviceAccount:
  create: true
