apiVersion: v1
kind: Secret
metadata:
  name: penpot-secrets
  namespace: penpot
type: Opaque
stringData:
  api-secret-key: <FILL-IN>

  db-username: <FILL-IN>
  db-password: <FILL-IN>
  db-hostname: <FILL-IN>
  db-name: <FILL-IN>

  redis-uri: <FILL-IN>

  smtp-username: <FILL-IN>
  smtp-password: <FILL-IN>
