apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-data
  namespace: adguard
spec:
  resources:
    requests:
      storage: 512Mi
  storageClassName: longhorn-locality-no-backup-retain # Should we backup config? probably
  accessModes:
    - ReadWriteOnce

