apiVersion: v1
kind: Secret
metadata:
  name: longhorn-cloudflare-r2-backups
  namespace: longhorn-system
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: <R2_S3_ACCESS_KEY>
  AWS_ENDPOINTS: https://<CLOUDFLARE_ACCOUNT_ID>.r2.cloudflarestorage.com
  AWS_SECRET_ACCESS_KEY: <R2_S3_SECRET_KEY>