---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pgadmin-config
  namespace: pgadmin
data:
  servers.json: |
    {
      "Servers": {
        "1": {
          "Name": "CNPG Cluster (Read-Write)",
          "Group": "niployments",
          "Host": "cnpg-cluster-rw.pg.svc.cluster.local",
          "Port": 5432,
          "MaintenanceDB": "postgres",
          "Username": "ni",
          "SSLMode": "prefer"
        },
        "2": {
          "Name": "CNPG Cluster (Read-Only)",
          "Group": "niployments",
          "Host": "cnpg-cluster-ro.pg.svc.cluster.local",
          "Port": 5432,
          "MaintenanceDB": "postgres",
          "Username": "ni",
          "SSLMode": "prefer"
        }
      }
    }