- name: Trust all ssh hosts if they don't exist yet
  hosts: all
  gather_facts: false
  tasks:
    - name: Accept SSH key for each host
      connection: local
      ansible.builtin.known_hosts:
        state: present
        name: "{{ hostvars[inventory_hostname]['ansible_ssh_host'] }}"
        key: "{{ lookup('pipe', 'ssh-keyscan -T 10 -H -t ssh-ed25519 ' + hostvars[inventory_hostname]['ansible_ssh_host']) }}"
