- name: Get internal interfaces
  hosts: all
  vars:
    target_network: 10.10.0.0
  tasks:
    - name: Get interface
      ansible.builtin.set_fact:
        target_interface: "{{ item }}"
        cacheable: true # cache it to other playbooks in this run use it
      when: (hostvars[inventory_hostname]['ansible_%s' % item] | default({})).get('ipv4', {}).get('network') == target_network
      loop: "{{ ansible_interfaces }}"
