---

- name: Configure bgp on routers
  hosts: routers

  tasks:
    - name: Install bird2 as dependency
      become: true
      ansible.builtin.apt:
        name: bird2
    - name: Configure bird2
      become: true
      ansible.builtin.template:
        src: templates/router-bird.conf.j2
        dest: /etc/bird/bird.conf
        mode: "644"
    - name: Restart bird2
      become: true
      ansible.builtin.systemd:
        name: bird
        state: restarted
