kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.resourceNames.pvc }}
  labels:
    {{- toYaml .Values.commonLabels | nindent 4 }}
spec:
  storageClassName: {{ .Values.volume.storageClassName }}
  accessModes:
    {{- toYaml .Values.volume.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.volume.storage }}
