apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.resourceNames.deployment }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- toYaml .Values.commonLabels | nindent 4 }}
spec:
  replicas: {{ .Values.minecraft.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.commonLabels.app | quote }}
  # wait for announcement + world save time
  terminationGracePeriodSeconds: {{ add .Values.minecraft.stopDelay 60 }}
  template:
    metadata:
      labels:
        {{- toYaml .Values.commonLabels | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      volumes:
      - name: minecraft-data
        persistentVolumeClaim:
          claimName: {{ .Values.resourceNames.pvc }}
      containers:
      - name: minecraft-server
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        env:
          - name: TYPE
            value: "{{ .Values.minecraft.type }}"
          - name: VERSION
            value: "{{ .Values.minecraft.version }}"
          - name: EULA
            value: {{ .Values.minecraft.eula | quote | upper }}
          - name: GAMEMODE
            value: "{{ .Values.minecraft.gamemode }}"
          - name: MOTD
            value: "{{ .Values.minecraft.motd }}"
          - name: ALLOW_FLIGHT
            value: {{ .Values.minecraft.allowFlight | quote | upper }}
          - name: SERVER_PORT
            value: "{{ .Values.minecraft.port }}"
          - name: ONLINE_MODE
            value: "{{ .Values.minecraft.onlineMode }}"
          - name: WHITELIST
            value: "{{ .Values.minecraft.whitelist }}"
          - name: ENABLE_WHITELIST
            value: "{{ .Values.minecraft.enableWhitelist }}"
          - name: STOP_SERVER_ANNOUNCE_DELAY
            value: "{{ .Values.minecraft.stopDelay }}"
          {{- if .Values.minecraft.modrinth.projects }}
          - name: MODRINTH_PROJECTS
            value: {{ join "," .Values.minecraft.modrinth.projects | quote }}
          {{- end }}
          {{- if .Values.minecraft.modrinth.downloadDependencies }}
          - name: MODRINTH_DOWNLOAD_DEPENDENCIES
            value: {{ .Values.minecraft.modrinth.downloadDependencies | quote }}
          {{- end }}
          {{- if .Values.minecraft.modrinth.allowedVersionType }}
          - name: MODRINTH_ALLOWED_VERSION_TYPE
            value: {{ .Values.minecraft.modrinth.allowedVersionType | quote }}
          {{- end }}
        ports:
        - containerPort: {{ .Values.minecraft.port }}
          name: minecraft
        volumeMounts:
          - name: minecraft-data
            mountPath: {{ .Values.volume.mountPath }}
        startupProbe:
          exec:
            command:
            - mc-monitor
            - status
            - -host
            - 127.0.0.1
            - -port
            - "{{ .Values.minecraft.port }}"
          initialDelaySeconds: {{ .Values.probes.startup.initialDelaySeconds }}
          failureThreshold: {{ .Values.probes.startup.failureThreshold }}
          periodSeconds: {{ .Values.probes.startup.periodSeconds }}
        readinessProbe:
          exec:
            command:
            - mc-monitor
            - status
            - -host
            - 127.0.0.1
            - -port
            - "{{ .Values.minecraft.port }}"
          initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
          periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
        livenessProbe:
          exec:
            command:
            - mc-monitor
            - status
            - -host
            - 127.0.0.1
            - -port
            - "{{ .Values.minecraft.port }}"
          initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
          periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.resourceNames.service }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- toYaml .Values.commonLabels | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.minecraft.port }}
      targetPort: minecraft
      name: minecraft
  selector:
    app: {{ .Values.commonLabels.app | quote }}
