# ServiceAccount
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "minecraft.fullname" . }}-restart-sa
  namespace: {{ .Release.Namespace }}

---

# Role
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "minecraft.fullname" . }}-restart-role
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    resourceNames: ["{{ .Values.minecraft.name }}-server"]
    verbs: ["get", "patch"]

---

# RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "minecraft.fullname" . }}-restart-rb
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ include "minecraft.fullname" . }}-restart-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "minecraft.fullname" . }}-restart-role
  apiGroup: rbac.authorization.k8s.io
