# CronJob
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.resourceNames.cronjob }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- toYaml .Values.commonLabels | nindent 4 }}
spec:
  schedule: {{ .Values.restart.schedule | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: {{ .Values.resourceNames.serviceAccount }}
          containers:
          - name: kubectl
            image: bitnami/kubectl:latest
            command:
                - /bin/sh
                - -c
                - kubectl rollout restart deployment/{{ .Values.resourceNames.deployment }}
          restartPolicy: OnFailure
