kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: minecraft-data-pvc
spec:
  storageClassName: longhorn-locality-no-backup
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.volume.storage }}
