apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ .Values.minecraft.name }}-irtcp
  namespace: {{ .Values.minecraft.namespace }} # shouldn't be necessary but just in case
spec:
  entryPoints:
    - minecraft
  routes:
    - match: minicraft.niaefeup.pt
      services:
        - name: {{ .Values.minecraft.name }}-server
          port: {{ .Values.minecraft.port }}
