FROM node:22-alpine AS build

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm ci

COPY . .
RUN npx tailwindcss -o twd.css -m
# tailwindcss -o

FROM nginx:alpine

# LOGO
COPY --from=build /app/logo-niaefeup.png /usr/share/nginx/html/logo-niaefeup.png
COPY --from=build /app/pages /user/share/nginx/html/pages


EXPOSE 8080