---
apiVersion: v1
kind: Secret
metadata:
  name: plausible-secret
  namespace: plausible-ni
type: Opaque
stringData:
  SECRET_KEY_BASE: <FILL-IN>
  SMTP_USER_NAME: <FILL-IN>
  MAILER_EMAIL: <FILL-IN>
  SMTP_USER_PWD: <FILL-IN>
  DATABASE_URL: <FILL-IN>
  TOTP_VAULT_KEY: <FILL-IN>