apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: website-cert
  namespace: plausible-ni
spec:
  secretName: website-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: plausible.niaefeup.pt
  dnsNames:
    - plausible.niaefeup.pt