apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-secrets
  namespace: nextcloud
type: Opaque
stringData:
  nextcloud-username: <FILL-IN>
  nextcloud-password: <FILL-IN>
  nextcloud-token: <FILL-IN>
  
  db-username: <FILL-IN>
  db-password: <FILL-IN>
  db-hostname: <FILL-IN>
  db-name: <FILL-IN>


