apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: valkey-pdb
  namespace: {{ include "valkey-sentinel.namespace" . }}
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: {{ include "valkey-sentinel.name" . }}
