apiVersion: v1
kind: Service
metadata:
  name: {{ include "valkey-sentinel.name" . }}-headless
  namespace: {{ include "valkey-sentinel.namespace" . }}
spec:
  clusterIP: None
  selector:
    app: {{ include "valkey-sentinel.name" . }}
  ports:
    - name: client
      port: {{ .Values.valkey.port }}
      targetPort: {{ .Values.valkey.port }}
    {{- if .Values.valkey.exporter.enabled }}
    - name: metrics
      port: {{ .Values.valkey.exporter.port }}
      targetPort: {{ .Values.valkey.exporter.port }}
    {{- end }}
