apiVersion: v1
kind: Service
metadata:
  name: {{ include "valkey-sentinel.sentinelName" . }}
  namespace: {{ include "valkey-sentinel.namespace" . }}
spec:
  selector:
    app: {{ include "valkey-sentinel.sentinelName" . }}
  ports:
    - name: sentinel
      port: {{ .Values.sentinel.port }}
      targetPort: {{ .Values.sentinel.port }}
