---

- name: Change hostname on router and nodes
  hosts: all
  tasks:
    - name: Change hostname
      become: true
      ansible.builtin.hostname:
        name: "{{ inventory_hostname }}"
    - name: Change hostname permanently
      become: true
      ansible.builtin.command:
        cmd: "hostnamectl set-hostname {{ inventory_hostname }}"
      changed_when: true
