---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: supertuxkart-server
  namespace: supertuxkart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: supertuxkart
  template:
    metadata:
      labels:
        app: supertuxkart
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: supertuxkart
        image: peucastro/stk-server:latest
        ports:
        - containerPort: 2757
          protocol: UDP
        - containerPort: 2759
          protocol: UDP
        env:
        - name: SERVER_NAME
          value: "NI SuperTuxKart Server"
        - name: SERVER_MODE
          value: "0"
        - name: SERVER_DIFFICULTY
          value: "1"
        - name: MAX_PLAYERS
          value: "20"
        - name: WAN_SERVER
          value: "false"
        - name: SERVER_PORT
          value: "2759"
        - name: LAN_SERVER_NAME
          value: "NI SuperTuxKart Server"
---
apiVersion: v1
kind: Service
metadata:
  name: supertuxkart-service
  namespace: supertuxkart
spec:
  selector:
    app: supertuxkart
  ports:
  - port: 2757
    targetPort: 2757
    protocol: UDP
    name: game
  - port: 2759
    targetPort: 2759
    protocol: UDP
    name: discovery
  type: NodePort
