---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteUDP
metadata:
  name: supertuxkart-game-ingress-udp
  namespace: supertuxkart
spec:
  entryPoints:
    - boobs
  routes:
  - services:
    - name: supertuxkart-service
      port: 2759
