---
apiVersion: v1
kind: ConfigMap
metadata:
  name: supertuxkart-config
  namespace: supertuxkart
data:
  server_config.xml: |
    <?xml version="1.0" encoding="utf-8"?>
    <server version="4">
      <mode value="0"/>
      <difficulty value="1"/>
      <max-players value="20"/>
      <server-name value="NI SuperTuxKart Server"/>
      <server-description value="NIAEFEUP SuperTuxKart Server"/>
      <wan-server value="false"/>
      <ai-karts value="4"/>
    </server>
