apiVersion: traefik.io/v1alpha1
kind: IngressRouteUDP
metadata:
  name: supertuxkart-udp
  namespace: supertuxkart
spec:
  entryPoints:
    - supertuxkart
  routes:
    - services:
        - name: supertuxkart-service
          port: 8008

---
