---
apiVersion: v1
kind: Secret
metadata:
  name: niddle-staging-secret
  namespace: niddle-staging
type: Opaque
stringData:
  DATABASE_USER: <FILL-IN>
  DATABASE_PASSWORD: <FILL-IN>
  DATABASE_HOST: <FILL-IN>
  DATABASE_PORT: <FILL-IN>
  DATABASE_NAME: <FILL-IN>
  JWT_SECRET: <FILL-IN>
