apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: teup-images-pvc
  namespace: teup-website
spec:
  storageClassName: longhorn-locality-no-backup-retain
  resources:
    requests:
      storage: 5Gi
  accessModes:
    - ReadWriteOnce