architecture: replication

auth:
  enabled: true
  password: "DevPass"
  sentinel: true

sentinel:
  enabled: true
  masterSet: "myprimary"
  quorum: 2
  downAfterMilliseconds: 5000
  failoverTimeout: 60000
  parallelSyncs: 1

  resources:
    requests:
      cpu: 25m
      memory: 50Mi

replica:
  replicaCount: 3
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
  persistence:
    enabled: true
    size: 512Mi
    accessModes:
      - ReadWriteOnce

primary:
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
  persistence:
    enabled: true
    size: 512Mi
    accessModes:
      - ReadWriteOnce

metrics:
  enabled: false

networkPolicy:
  enabled: true
