# Default values for minecraft.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

minecraft:
  name: "minicraft"
  type: "PAPER"
  version: "26.1.2"
  gamemode: "survival"
  motd: "Bem-vindos ao miNIcraft!"
  port: 30565
  onlineMode: false
  enableWhitelist: true
  whitelist: rubuy74, SellingJaguar, miltilde, peu, seymm, ramaa____, AnalyticalT, guicnunes, ttoino, Flumpe6, RickyF, Marianita21, Emerald_Scammer, Tomili2000, Montanelas, Darguima, jipinho, dtvf7, Sp1kyBtw, skaffoldf, GunaMalvado, FrozenHart, Pinho, pmpy_
  heap_memory: 4G

volume:
  storage: 6Gi
  storageClassName: longhorn-locality-no-backup
  mountPath: /data

resources:
  limits:
    memory: 6Gi
  requests:
    memory: 4Gi
