# Default values for minecraft.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

minecraft:
  name: "minicraft"
  type: "PAPER"
  version: "26.1.2"
  gamemode: "survival"
  motd: "Isto é a mensagem do dia." # Message of the Day
  port: 30565
  onlineMode: false
  enableWhitelist: true

volume:
  storage: 3Gi
  storageClassName: longhorn-locality-no-backup
  mountPath: /data
  configMap:
    name: minecraft-config

resources:
  limits:
    memory: 2Gi
  requests:
    memory: 1.5Gi
