---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  namespace: ni-website
spec:
  storageClassName: longhorn-locality-retain
  resources:
    requests:
      storage: 3Gi
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: public-pvc
  namespace: ni-website
spec:
  storageClassName: longhorn-locality-retain
  resources:
    requests:
      storage: 2Gi
  accessModes:
    - ReadWriteOnce