defaultVaultConnection:
  enabled: true
  address: "https://vault.vault.svc.cluster.local:8200"
  skipTLSVerify: false
controller:
  manager:
    clientCache:
      persistenceModel: direct-encrypted
      storageEncryption:
        enabled: true
        mount: demo-auth-mount
        keyName: vso-client-cache
        namespace: vault-operator
        transitMount: demo-transit
        kubernetes:
          role: auth-role-operator
          serviceAccount: vault-operator
