#https://developer.hashicorp.com/vault/docs/platform/k8s/helm/configuration
global:
  enabled: true
  tlsDisable: false
  namespace: vault

server:
  dev:
    enabled: false
  logLevel: debug
  volumes:
    - name: tls
      secret:
        secretName: trust-manager-ca-secret
  volumeMounts:
    - name: tls
      mountPath: "/opt/vault/tls"
      readOnly: true

ui:
  enabled: true
  serviceType: "LoadBalancer"
  targetPort: 8200
  externalPort: 8200

dataStorage:
  enabled: true
  size: 2Gi
  storageClass: longhorn-locality-retain
  mountPath: "/opt/vault/raft"
  accessMode: ReadWriteOnce

ha:
  enabled: true
  config: |
    ui = true
    disable_mlock = true # avoids out of memory errors by blocking swapping of its virtual pages
    
    listener "tcp" {
      address = "0.0.0.0:8200"
      tls_disable = "false"
      tls_cert_file      = "/opt/vault/tls/tls.crt"
      tls_key_file       = "/opt/vault/tls/tls.key"
      tls_client_ca_file = "/opt/vault/tls/ca.crt" # certificate of the CA root
    }

    storage "raft" {
      path = "/opt/vault/raft"
    }
  raft:
    enabled: true
    replicas: 3
       
injector:
  enabled: "false"
