name: ansible-lint
on:
  pull_request:
  push:
    branches:
      - main
      - fix/ansible-lint


jobs:
  build:
    name: Ansible Lint # Naming the build is important to use it as a status check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get --assume-yes --no-install-recommends install python3-pip
          python3 -m pip install --user -U ansible ansible-lint jmespath 


      - name: Run ansible-lint
        run: |
          ansible-lint
  
      - name: Upload sarif
        if: always()
        uses: github/codeql-action/upload-sarif@v2
        with:
         sarif_file: ansible.sarif
         category: ansible-lint
