name: pulumi-lint

on:
  pull_request: 
    branches: [ "main" ]
    paths: [ "services/pulumi/**" ]
  push:
    branches: [ "main" ]
    paths: [ "services/pulumi/**" ]

jobs:
  format:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Run prettier
        run: pnpm run prettier

  lint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Run ESLint
        run: pnpm run lint
