kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-strict-local-retain
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: "Retain"
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "1"
  staleReplicaTimeout: "720"
  fromBackup: ""
  fsType: "ext4"
  dataLocality: "strict-local"
  replicaAutoBalance: "ignored"
#  diskSelector: "ssd,fast"
#  nodeSelector: "storage,fast"
  recurringJobSelector: '[{"name":"default", "isGroup":true},{"name":"backup", "isGroup":true}]'
