kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-locality-retain
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: "Retain"
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "2880"
  fromBackup: ""
  fsType: "ext4"
  dataLocality: "best-effort"
  replicaAutoBalance: "least-effort"
#  diskSelector: "ssd,fast"
#  nodeSelector: "storage,fast"
  recurringJobSelector: '[{"name":"default", "isGroup":true},{"name":"backup", "isGroup":false}]'
